---
title: "CI_online_clean"
author: "Alberte Seeberg"
date: "2024-04-10"
output:
  html_document:
    df_print: paged
---


```{r include = FALSE}
#set work directory
setwd('/Users/au555044/Desktop/CI_Groove_Project/Online/Online_CI/Data_CI')

#load packages
library(tidyverse)
library(ggplot2)
library(cowplot)
library(lme4)
library(afex)
library(ggpubr)
library(rmcorr)
library(car)
library(dplyr)
library(emmeans)
library(jtools)
library(kableExtra)
library(sjPlot)
```

########                               ~*~*~*~*~*~*~*~*~*~*                             ##########
#                                         Preprocessing!                                         #
##############                         *~*~*~*~*~*~*~*~*~*~                           ###########
```{r}

#read data
rhythms = read.csv2('V3_CI_subset_9.csv')
df_m = read.csv2('CI_on.csv')
df_m = df_m[-1]
df_m$Version[df_m$Version == 'full'] = 'SN+BD+HH'
df_m$Version = factor(df_m$Version, levels = c('SN+BD+HH', 'SN+BD','SN+HH','SN'))
df_m$yrsTraining = as.factor(df_m$yrsTraining)
df_m$ID = as.factor(df_m$ID)
df_m$dizziness = as.factor(df_m$dizziness)
df_m$sex = as.factor(df_m$sex)
df_m$tinnitus = as.factor(df_m$tinnitus)
df_m$hearingAids = as.factor(df_m$hearingAids)
df_m$CIs = as.factor(df_m$CIs)
df_m$CI_brand = as.factor(df_m$CI_brand)
df_m$Processor = as.factor(df_m$Processor)
df_m$CI_exp = as.factor(df_m$CI_exp)
df_m$ratingType[df_m$ratingType == 'move'] = 'Wanting to Move'
df_m$ratingType[df_m$ratingType == 'pleasure'] = 'Experienced Pleasure'

#Adding a column with wSI for full version for all versions of each rhythm to test per rhythm
wSI_f = subset(df_m, Version %in% "SN+BD+HH")
wSI_f = wSI_f %>% 
distinct(stimNumber, wSI)

wSI_f = wSI_f %>% 
  rename(
    wSI_full = wSI,
    )

df_m = left_join(df_m, wSI_f, by = "stimNumber")


demo = df_m %>% 
distinct(ID, age, sex, origin, tinnitus, hearingAids, CIs, CI_brand, Processor, yrsTraining, CI_exp, CI_satisfaction, sound)

demo$origin[demo$origin %in% c('U.S.A.', 'United States','United States ', 'United States Of America', 'US')] <- 'USA'
demo$origin[demo$origin %in% 'SWEDEN'] <- 'Sweden'
demo$origin=as.factor(demo$origin)	

df_wide=read.csv2("CI_on_wide.csv")
df_wide$dizziness = as.factor(df_wide$dizziness)
df_wide$practice = as.factor(df_wide$practice)
df_wide$yrsStop = as.factor(df_wide$yrsStop)
df_wide$yrsTraining = as.factor(df_wide$yrsTraining)
df_wide$timeListen = as.factor(df_wide$timeListen)
df_wide$ID = as.factor(df_wide$ID)

```


########                               ~*~*~*~*~*~*~*~*~*~*                             ##########
#                                            Plots!                                             #
##############                         *~*~*~*~*~*~*~*~*~*~                           ###########


```{r}

#CREATE PLOT FOR ORIGIN

# Count the occurrences of each level in origin
counts <- demo %>%
  count(origin)

# Filter levels with a count of 1
single_count_levels <- counts$origin[counts$n == 1]

# Create a new variable, grouping all levels with a count of 1 into "Other"
demo <- demo %>%
  mutate(origin = fct_collapse(origin, Other = as.character(single_count_levels)))

# Reorder by count in ascending order
demo$origin <- fct_infreq(demo$origin)

# Move "Other" to the last position
demo$origin <- fct_relevel(demo$origin, "Other", after = Inf)

# Create the plot
nat_ci=ggplot(demo, aes(x = origin)) + 
  geom_bar(position = "dodge", fill = "darkgoldenrod1", color = "black", linewidth = 0.2) +
  labs(
    x = NULL,             # Label for the x-axis
    y = NULL                    # Label for the y-axis
  ) +
  theme_minimal(base_size = 18)

# CHECK CORRELATION BTW MOVE AND PLEASURE

#Account for repeated measures
corval = rmcorr(ID, move, pleasure, df_wide)
plot(corval)
corval

# Collapse data to just have one rating to plot

df_c = aggregate(df_m$rating,by=list(df_m$ID, df_m$Version, df_m$wSI, df_m$wSI_full), mean)

df_c = plyr::rename(df_c, c("Group.1"="ID"))
df_c = plyr::rename(df_c, c("Group.2"="Version"))
df_c = plyr::rename(df_c, c("Group.3"="wSI"))
df_c = plyr::rename(df_c, c("Group.4"="wSI_full"))
df_c = plyr::rename(df_c, c("x"="rating"))

#Plot for inverted U - CI users

p_ci =ggplot(df_c, aes(x = wSI_full, y= rating, group = Version, colour = Version))+
  #geom_point(aes(colour = rhythmType))+
  ylim(0,100)+
  geom_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE)+
  geom_rug(sides="b", colour= "black")+
  ggtitle('CI Users')+
  ylab("Rating")+xlab("Degree of syncopation") + theme_minimal(base_size = 15) + scale_color_brewer(palette="Dark2")+theme(axis.title.x=element_blank(), axis.title.y=element_blank(), legend.position="none",plot.title = element_text(hjust = 0.5))

```

########                               ~*~*~*~*~*~*~*~*~*~*                             ##########
#                                          Analysis WSI                                         #
##############                         *~*~*~*~*~*~*~*~*~*~                           ###########

### Mixed effects models
```{r }
m0 <- lmer(rating ~ 1 + (poly(wSI_full,2)|ID), data = df_m,
           REML = FALSE, control = lmerControl(optimizer = "nlminbwrap", calc.derivs = FALSE))

m1 = update(m0,.~.+poly(wSI_full,2)) 
m2 = update(m1,.~.+Version) 
m3 = update(m2,.~.+poly(wSI_full,2):Version)

anova(m0, m1, m2, m3)

summary(m3)

tab_model(m3, show.stat = TRUE, show.df = TRUE, show.se = TRUE, show.ci = FALSE, string.pred = "Independent variables", string.stat = "t-val", col.order = c("est", "se", "stat", "df", "p"), file = "m3_CI_table_fullref.doc")
```

```{r}
#Testing with SN+HH reference in version

df_m$Version = factor(df_m$Version, levels = c("SN+HH", "SN", "SN+BD", "SN+BD+HH"))

m0 <- lmer(rating ~ 1 + (poly(wSI_full,2)|ID), data = df_m,
           REML = FALSE, control = lmerControl(optimizer = "nlminbwrap", calc.derivs = FALSE))

m1 = update(m0,.~.+poly(wSI_full,2)) 
m2 = update(m1,.~.+Version) 
m3 = update(m2,.~.+poly(wSI_full,2):Version)

anova(m0, m1, m2, m3)

summary(m3)

#export table to word format
tab_model(m3, show.stat = TRUE, show.df = TRUE, show.se = TRUE, show.ci = FALSE, string.pred = "Independent variables", string.stat = "t-val", col.order = c("est", "se", "stat", "df", "p"), file = "m3_CI_table_SNHHref.doc")

```


### Anova, post hocs
```{r message = FALSE}
options(digits =3)
#type III ANOVA
anova(m3)

#Post hoc contrasts at syncopation index 0, 20, 40, 60, 80
emR <- emmeans(m3,  ~ Version, 'wSI_full', at = list(wSI_full = c(0,20,40,60,80)), pbkrtest.limit = 5280)

# goes in consecutive order - not including all contrasts
emR %>% 
    contrast('consec', reverse = TRUE) %>% 
    confint(by = NULL, adjust = "holm") 

#holm p val
emR %>% 
    contrast('consec', reverse = TRUE, adjust = "holm")

```

### Diagnostic plots of final model
```{r message = FALSE}
#Diagnostic plots
qqPlot(resid(m3)) 
hist(resid(m3)) 

#Homoscedasticity and linearity

# Fitted vs. residual plot (linearity)
plot(m3, type = c('p', 'smooth'))

# Scale-location plot (homoscedasticity)
plot(m3, sqrt(abs(resid(.))) ~ fitted(.), type = c("p", "smooth"))

# Observed versus fitted values by Version
plot(m3, rating ~ fitted(.) | Version, abline = c(0,1))
```

### Checking results without CI users with HAs listening through headphones/speakers
```{r message = FALSE}
df_noHA = df_m %>%
  filter(!(hearingAids == "One" & sound %in% c("Headphones", "Speakers")))

plot_data = aggregate(df_noHA$rating,by=list(df_noHA$ID, df_noHA$Version, df_noHA$wSI, df_noHA$wSI_full), mean)

plot_data = plyr::rename(plot_data, c("Group.1"="ID"))
plot_data = plyr::rename(plot_data, c("Group.2"="Version"))
plot_data = plyr::rename(plot_data, c("Group.3"="wSI"))
plot_data = plyr::rename(plot_data, c("Group.4"="wSI_full"))
plot_data = plyr::rename(plot_data, c("x"="rating"))

ggplot(plot_data, aes(x = wSI_full, y= rating, group = Version, colour = Version))+
  #geom_point(aes(colour = rhythmType))+
  ylim(0,100)+
  geom_smooth(method = "lm", formula = y ~ poly(x, 2), se = TRUE)+
  ggtitle('CI Users - % HAs and speakers/headphones')+
  ylab("Rating")+xlab("Degree of syncopation") + theme_minimal(base_size = 13) + scale_color_brewer(palette="Dark2")+theme(plot.title = element_text(hjust = 0.5))
```

